version: '3'

services:
  <influxdb-service-name>:
    image: influxdb:latest
    container_name: <influxdb_container_name>
    ports:
      - 8086:8086
    volumes:
      - </some_folder>:/var/lib/influxdb
    environment:
      - INFLUXDB_HTTP_AUTH_ENABLED=true
      - INFLUXDB_MONITOR_STORE_ENABLED=false
      - INFLUXDB_DB=<db>
      - INFLUXDB_ADMIN_USER=<admin>
      - INFLUXDB_ADMIN_PASSWORD=<pw1>
      - INFLUXDB_USER=<user>
      - INFLUXDB_USER_PASSWORD=<pw2>
      - INFLUXDB_READ_USER=<read>
      - INFLUXDB_READ_USER_PASSWORD=<pw3>
    restart: unless-stopped